global:
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      valueFrom: {secretKeyRef: {name: authentik-db-app, key: host}}
    - name: AUTHENTIK_POSTGRESQL__PORT
      valueFrom: {secretKeyRef: {name: authentik-db-app, key: port}}
    - name: AUTHENTIK_POSTGRESQL__NAME
      valueFrom: {secretKeyRef: {name: authentik-db-app, key: dbname}}
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom: {secretKeyRef: {name: authentik-db-app, key: username}}
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom: {secretKeyRef: {name: authentik-db-app, key: password}}

authentik:
  existingSecret:
    secretName: authentik

postgresql:
  enabled: false

server:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

worker:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
