# =============================================================================
# REDIS OPERATOR VALUES
# =============================================================================
# Docs: https://redis-operator.opstree.dev/
# =============================================================================

redisOperator:
  imagePullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi
