apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: credentials
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
    - group: external-secrets.io
      kind: ClusterExternalSecret
      jqPathExpressions:
        - .spec.externalSecretSpec.data[].remoteRef.conversionStrategy
        - .spec.externalSecretSpec.data[].remoteRef.decodingStrategy
        - .spec.externalSecretSpec.data[].remoteRef.metadataPolicy
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: charts/credentials
    helm:
      valuesObject:
        global:
          tailscale:
            clientId: {{ .Values.global.tailscale.clientId }}
          auth0:
            clientId: {{ .Values.global.auth0.clientId }}
          dockerhub:
            username: {{ .Values.global.dockerhub.username }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
