# =============================================================================
# LONGHORN - DISTRIBUTED BLOCK STORAGE FOR KUBERNETES
# =============================================================================
# Docs: https://longhorn.io/docs/1.10.1/deploy/install/install-with-argocd/
#
# Provides persistent volumes with replication.
# No changes needed - uses official Helm chart.
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    # Wave 3: storage
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: "1.10.1"
      helm:
        valueFiles:
          - $values/helm-values/core/longhorn.yaml
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        tier: infrastructure
        team: platform
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      refresh: true
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
