# =============================================================================
# NODE TUNING - Kernel parameters for observability stack
# =============================================================================
# Fixes inotify limits for Alloy log collection
# Must run BEFORE monitoring stack (wave 30)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-tuning
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: manifests/core/node-tuning
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
