# =============================================================================
# REDIS OPERATOR - OT-CONTAINER-KIT
# =============================================================================
# Docs: https://redis-operator.opstree.dev/
# Helm: https://github.com/OT-CONTAINER-KIT/helm-charts
#
# Provides:
# - Declarative Redis standalone/replication/cluster management
# - Redis Sentinel for HA
# - Integrated Prometheus monitoring (redis-exporter)
# - TLS support
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://ot-container-kit.github.io/helm-charts/
      chart: redis-operator
      targetRevision: "0.22.2"
      helm:
        valueFiles:
          - $values/helm-values/core/redis-operator.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: redis-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        tier: infrastructure
        team: platform
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
