# =============================================================================
# ARGOCD IMAGE UPDATER - AUTOMATIC CONTAINER IMAGE UPDATES
# =============================================================================
# Docs: https://argocd-image-updater.readthedocs.io/
# Chart: https://github.com/argoproj/argo-helm/tree/main/charts/argocd-image-updater
#
# Monitors container registries for new image versions and updates
# ArgoCD Applications automatically based on annotations.
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    # Wave 7: after external-secrets infrastructure
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cicd
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-image-updater
      targetRevision: "1.0.1"
      helm:
        valueFiles:
          - $values/helm-values/cicd/argocd-image-updater.yaml
        valuesObject:
          config:
            registries:
              - name: Docker Hub
                api_url: https://registry-1.docker.io
                prefix: docker.io
                ping: yes
                defaultns: library
                default: true
                credentials: pullsecret:argocd/dockerhub-credentials
            log.level: info
          metrics:
            enabled: true
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      refresh: true
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
