# =============================================================================
# GRAFANA ALLOY VALUES
# =============================================================================
# Docs: https://grafana.com/docs/alloy/latest/
# Collects Kubernetes pod logs and sends to Loki
# =============================================================================

# Deploy as DaemonSet to collect logs from all nodes
controller:
  type: daemonset

# Resources - per Grafana docs:
# https://grafana.com/docs/alloy/latest/introduction/estimate-resource-usage/
# Logs: ~1 CPU / 120Mi per 1 MiB/s, real-world often 300Mi-1Gi
# k3s-home: moderate limit, increase if OOM occurs
alloy:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi

  # Mount paths for log collection
  mounts:
    varlog: true
    dockercontainers: true

  # Alloy configuration
  # https://grafana.com/docs/alloy/latest/collect/logs-in-kubernetes/
  configMap:
    content: |
      // =============================================================================
      // KUBERNETES LOG COLLECTION
      // =============================================================================
      // Docs: https://grafana.com/docs/alloy/latest/collect/logs-in-kubernetes/

      // Discover Kubernetes pods
      discovery.kubernetes "pods" {
        role = "pod"
      }

      // Relabel to extract useful metadata
      discovery.relabel "pod_logs" {
        targets = discovery.kubernetes.pods.targets

        // Keep only running pods
        rule {
          source_labels = ["__meta_kubernetes_pod_phase"]
          regex         = "Pending|Succeeded|Failed|Unknown"
          action        = "drop"
        }

        // Set namespace label
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }

        // Set pod label
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }

        // Set container label
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }

        // Set app label from standard labels
        rule {
          source_labels = ["__meta_kubernetes_pod_label_app"]
          target_label  = "app"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          target_label  = "app"
        }

        // Set job label
        rule {
          source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
          separator     = "/"
          target_label  = "job"
        }

        // Set log file path
        rule {
          source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
          separator     = "/"
          target_label  = "__path__"
          replacement   = "/var/log/pods/*$1/*.log"
        }
      }

      // Tail log files
      loki.source.kubernetes "pod_logs" {
        targets    = discovery.relabel.pod_logs.output
        forward_to = [loki.process.pod_logs.receiver]
      }

      // Process logs - add cluster label
      // Source: apps/values.yaml -> global.cluster
      // NOTE: Raw config - must sync manually with global.cluster value
      loki.process "pod_logs" {
        stage.static_labels {
          values = {
            cluster = "k3s-home",
          }
        }

        forward_to = [loki.write.loki.receiver]
      }

      // Send to Loki
      loki.write "loki" {
        endpoint {
          url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        }
      }

# ServiceAccount for RBAC
serviceAccount:
  create: true

# RBAC for pod discovery
rbac:
  create: true
