apiVersion: v2
name: victoria-metrics-k8s-stack
description: Small-cluster VictoriaMetrics and Grafana wrapper
type: application
version: 0.1.0
dependencies:
  - name: victoria-metrics-k8s-stack
    version: "0.87.0"
    repository: https://victoriametrics.github.io/helm-charts
