provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: token

extraArgs:
  - --cloudflare-proxied
  - --cloudflare-dns-records-per-page=5000
  - --txt-prefix=extdns-

# domainFilters set via valuesObject in Application template
# Source: apps/values.yaml -> global.domain
domainFilters: []

sources:
  - ingress

policy: sync

txtOwnerId: external-dns

logLevel: info

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi
