# =============================================================================
# PROTECTED SERVICES
# =============================================================================
# Tailscale LoadBalancers + NGINX Ingresses + oauth2-proxy for internal services
# Configure in: charts/protected-services/values.yaml
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: protected-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "17"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: network
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: charts/protected-services
    helm:
      valuesObject:
        global:
          tailnet: {{ .Values.global.tailnet }}
          domain: {{ .Values.global.domain }}
          auth0:
            domain: {{ .Values.global.auth0.domain }}
            clientId: {{ .Values.global.auth0.clientId }}
          cloudflare:
            tunnelId: {{ .Values.global.cloudflare.tunnelId }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
